export const METRICS = [
  // 1. Executive Summary (Uses aggregates of other domains, but let's define 3 overall KPIs)
  {
    id: "exec.health",
    name: "Overall Health Score",
    domain: "executive-summary",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 90,
    warn: 75,
    definition: "Composite index of operational, financial, and delivery health across all IT functions.",
    formula: "Weighted average of domain health scores",
    grain: "portfolio × month",
    owner: "CIO",
    source: "Aggregated from underlying domains",
    refresh: "monthly",
    quality: 0.95,
    certified: true,
    lineage: [["Metric: exec.health", "certified 2025-01"]],
  },
  {
    id: "exec.ah_health",
    name: "AH Health Score",
    domain: "executive-summary",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 90,
    warn: 75,
    definition: "Composite index for Animal Health IT.",
    formula: "Weighted average of AH domain scores",
    grain: "BU × month",
    owner: "AH CIO",
    source: "Aggregated",
    refresh: "monthly",
    quality: 0.95,
    certified: true,
    lineage: [["Metric: exec.ah_health", "certified 2025-01"]],
  },
  {
    id: "exec.hp_health",
    name: "HP Health Score",
    domain: "executive-summary",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 90,
    warn: 75,
    definition: "Composite index for Human Pharma IT.",
    formula: "Weighted average of HP domain scores",
    grain: "BU × month",
    owner: "HP CIO",
    source: "Aggregated",
    refresh: "monthly",
    quality: 0.95,
    certified: true,
    lineage: [["Metric: exec.hp_health", "certified 2025-01"]],
  },

  // 2. Business Trust
  {
    id: "trust.nps",
    name: "NPS Score",
    domain: "business-trust",
    unit: "pts",
    decimals: 0,
    direction: "up",
    target: 40,
    warn: 20,
    definition: "Net Promoter Score from quarterly business stakeholder surveys.",
    formula: "% Promoters - % Detractors",
    grain: "stakeholder × quarter",
    owner: "Business Partnering",
    source: "Qualtrics",
    refresh: "quarterly",
    quality: 0.92,
    certified: true,
    lineage: [["Qualtrics", "Survey Responses"], ["Metric: trust.nps", "certified 2025-01"]],
  },
  {
    id: "trust.escalations",
    name: "Escalations (MTD)",
    domain: "business-trust",
    unit: "count",
    decimals: 0,
    direction: "down",
    target: 5,
    warn: 15,
    definition: "Number of issues escalated to IT executive leadership.",
    formula: "Count of escalation tickets",
    grain: "issue × month",
    owner: "Service Ops",
    source: "ServiceNow",
    refresh: "daily",
    quality: 0.98,
    certified: true,
    lineage: [["ServiceNow", "Escalation Table"], ["Metric: trust.escalations", "certified 2025-01"]],
  },
  {
    id: "trust.adoption",
    name: "Adoption Rate",
    domain: "business-trust",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 80,
    warn: 60,
    definition: "Percentage of target user base actively using key deployed platforms.",
    formula: "Active Users / Licensed Users",
    grain: "product × month",
    owner: "Product Management",
    source: "Azure AD + App Insights",
    refresh: "monthly",
    quality: 0.85,
    certified: false,
    lineage: [["Metric: trust.adoption", "uncertified"]],
  },

  // 3. Operational Health
  {
    id: "ops.availability",
    name: "Availability",
    domain: "operational-health",
    unit: "%",
    decimals: 2,
    direction: "up",
    target: 99.9,
    warn: 99.4,
    definition: "Weighted uptime of tier-1 services during published service windows.",
    formula: "1 - Σ(unplanned_down_min × users) / Σ(window_min × users)",
    grain: "service × day",
    owner: "Service Ops",
    source: "ServiceNow + Datadog synthetics",
    refresh: "hourly",
    quality: 0.98,
    certified: true,
    lineage: [
      ["Datadog", "synthetic + RUM checks"],
      ["ServiceNow", "outage records, tier-1 CI list"],
      ["Metric: ops.availability", "certified 2025-08"],
    ],
  },
  {
    id: "ops.major_incidents",
    name: "Major Incidents",
    domain: "operational-health",
    unit: "count",
    decimals: 0,
    direction: "down",
    target: 2,
    warn: 8,
    definition: "Count of P1/P2 incidents impacting tier-1 business services.",
    formula: "Count(Incident WHERE priority IN (1,2))",
    grain: "incident × month",
    owner: "Service Ops",
    source: "ServiceNow",
    refresh: "daily",
    quality: 0.99,
    certified: true,
    lineage: [["ServiceNow", "Incident Management"], ["Metric: ops.major_incidents", "certified"]],
  },
  {
    id: "ops.sla_achievement",
    name: "SLA Achievement",
    domain: "operational-health",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 95,
    warn: 85,
    definition: "Percentage of service desk tickets resolved within SLA.",
    formula: "Tickets met SLA / Total Tickets",
    grain: "ticket × month",
    owner: "Service Desk",
    source: "ServiceNow",
    refresh: "daily",
    quality: 0.95,
    certified: true,
    lineage: [["ServiceNow", "SLA Table"], ["Metric: ops.sla_achievement", "certified"]],
  },

  // 4. Strategic Portfolio
  {
    id: "port.health",
    name: "Portfolio Health",
    domain: "strategic-portfolio",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 85,
    warn: 70,
    definition: "Percentage of strategic projects currently tracked as Green/On-Track.",
    formula: "Projects(Green) / Projects(Total)",
    grain: "project × month",
    owner: "PMO",
    source: "Project Ledger",
    refresh: "weekly",
    quality: 0.90,
    certified: true,
    lineage: [["Project Ledger", "Status Reports"], ["Metric: port.health", "certified"]],
  },
  {
    id: "port.on_track",
    name: "Projects On Track",
    domain: "strategic-portfolio",
    unit: "count",
    decimals: 0,
    direction: "up",
    target: 30,
    warn: 20,
    definition: "Count of strategic projects currently On-Track.",
    formula: "Count(Projects WHERE status='On-Track')",
    grain: "project × month",
    owner: "PMO",
    source: "Project Ledger",
    refresh: "weekly",
    quality: 0.90,
    certified: true,
    lineage: [["Project Ledger", "Status Reports"]],
  },
  {
    id: "port.at_risk",
    name: "Projects At Risk",
    domain: "strategic-portfolio",
    unit: "count",
    decimals: 0,
    direction: "down",
    target: 5,
    warn: 15,
    definition: "Count of strategic projects currently At-Risk or Off-Track.",
    formula: "Count(Projects WHERE status IN ('At-Risk', 'Off-Track'))",
    grain: "project × month",
    owner: "PMO",
    source: "Project Ledger",
    refresh: "weekly",
    quality: 0.90,
    certified: true,
    lineage: [["Project Ledger", "Status Reports"]],
  },

  // 5. Delivery & Value
  {
    id: "del.benefits",
    name: "Benefits Realization",
    domain: "delivery-value",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 90,
    warn: 70,
    definition: "Percentage of committed business value actually realized 6 months post-launch.",
    formula: "Realized Value / Business Case Value",
    grain: "project × quarter",
    owner: "Value Office",
    source: "Finance System",
    refresh: "quarterly",
    quality: 0.75,
    certified: false,
    lineage: [["Metric: del.benefits", "uncertified"]],
  },
  {
    id: "del.ttv",
    name: "Time to Value",
    domain: "delivery-value",
    unit: "mos",
    decimals: 1,
    direction: "down",
    target: 3.5,
    warn: 6.0,
    definition: "Average months from project funding to first production release.",
    formula: "Avg(Release Date - Funding Date)",
    grain: "project × month",
    owner: "Engineering",
    source: "Jira + Project Ledger",
    refresh: "monthly",
    quality: 0.88,
    certified: true,
    lineage: [["Jira", "Epics"], ["Project Ledger", "Funding"], ["Metric: del.ttv", "certified"]],
  },
  {
    id: "del.velocity",
    name: "Delivery Velocity",
    domain: "delivery-value",
    unit: "pts",
    decimals: 0,
    direction: "up",
    target: 100,
    warn: 70,
    definition: "Normalized measure of software output across agile teams.",
    formula: "Sum(Story Points) / Team Size",
    grain: "team × sprint",
    owner: "Engineering",
    source: "Jira",
    refresh: "bi-weekly",
    quality: 0.85,
    certified: true,
    lineage: [["Jira", "Sprints"]],
  },

  // 6. Financial Health
  {
    id: "fin.budget_var",
    name: "Budget vs Actual (YTD)",
    domain: "financial-health",
    unit: "%",
    decimals: 0,
    direction: "flat",
    target: 100,
    warn: 105,
    definition: "Year-to-date actual spend vs planned budget.",
    formula: "Actual Spend / Planned Budget",
    grain: "cost center × month",
    owner: "Finance",
    source: "SAP",
    refresh: "monthly",
    quality: 0.99,
    certified: true,
    lineage: [["SAP", "GL"], ["Metric: fin.budget_var", "certified"]],
  },
  {
    id: "fin.forecast_acc",
    name: "Forecast Accuracy",
    domain: "financial-health",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 95,
    warn: 85,
    definition: "Accuracy of monthly financial forecasts.",
    formula: "1 - abs(Actual - Forecast) / Forecast",
    grain: "cost center × month",
    owner: "Finance",
    source: "SAP",
    refresh: "monthly",
    quality: 0.99,
    certified: true,
    lineage: [["SAP", "GL"]],
  },
  {
    id: "fin.runrate",
    name: "Run vs Change",
    domain: "financial-health",
    unit: "%",
    decimals: 0,
    direction: "flat",
    target: 50,
    warn: 65,
    definition: "Percentage of IT budget spent on 'Run' (operations) vs 'Change' (projects).",
    formula: "Run Spend / Total Spend",
    grain: "cost center × month",
    owner: "Finance",
    source: "SAP",
    refresh: "monthly",
    quality: 0.95,
    certified: true,
    lineage: [["SAP", "GL"]],
  },

  // 7. People & Capability
  {
    id: "peo.engagement",
    name: "Engagement Score",
    domain: "people-capability",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 80,
    warn: 65,
    definition: "Employee engagement score from pulse surveys.",
    formula: "Favorable Responses / Total Responses",
    grain: "employee × quarter",
    owner: "HR",
    source: "Workday",
    refresh: "quarterly",
    quality: 0.90,
    certified: true,
    lineage: [["Workday", "Surveys"]],
  },
  {
    id: "peo.open_pos",
    name: "Open Positions",
    domain: "people-capability",
    unit: "%",
    decimals: 0,
    direction: "down",
    target: 10,
    warn: 15,
    definition: "Percentage of approved headcount currently unfilled.",
    formula: "Open Reqs / Total Headcount",
    grain: "department × month",
    owner: "HR",
    source: "Workday",
    refresh: "weekly",
    quality: 0.98,
    certified: true,
    lineage: [["Workday", "Recruiting"]],
  },
  {
    id: "peo.retention",
    name: "Retention (TTM)",
    domain: "people-capability",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 95,
    warn: 85,
    definition: "Trailing 12-month employee retention rate.",
    formula: "1 - (Departures / Avg Headcount)",
    grain: "department × month",
    owner: "HR",
    source: "Workday",
    refresh: "monthly",
    quality: 0.99,
    certified: true,
    lineage: [["Workday", "Core HR"]],
  },

  // 8. AI & Innovation
  {
    id: "ai.readiness",
    name: "AI Readiness",
    domain: "ai-innovation",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 85,
    warn: 60,
    definition: "Organizational readiness for AI adoption (skills + data quality).",
    formula: "Weighted index of data quality and certified practitioners",
    grain: "department × quarter",
    owner: "CDO",
    source: "LMS + Data Catalog",
    refresh: "quarterly",
    quality: 0.80,
    certified: false,
    lineage: [["Metric: ai.readiness", "uncertified"]],
  },
  {
    id: "ai.adoption",
    name: "AI Adoption Index",
    domain: "ai-innovation",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 80,
    warn: 50,
    definition: "Percentage of teams actively using approved AI tools.",
    formula: "Active AI Teams / Total Teams",
    grain: "team × month",
    owner: "Innovation",
    source: "Tool Telemetry",
    refresh: "monthly",
    quality: 0.85,
    certified: true,
    lineage: [["Telemetry", "Logs"]],
  },
  {
    id: "ai.prod_cases",
    name: "AI Use Cases in Production",
    domain: "ai-innovation",
    unit: "count",
    decimals: 0,
    direction: "up",
    target: 20,
    warn: 10,
    definition: "Number of AI/ML models deployed to production environments.",
    formula: "Count(Models WHERE status='Production')",
    grain: "model × month",
    owner: "AI Center of Excellence",
    source: "Model Registry",
    refresh: "monthly",
    quality: 0.95,
    certified: true,
    lineage: [["MLflow", "Registry"]],
  },

  // 9. Cyber & Compliance
  {
    id: "cyb.posture",
    name: "Security Posture",
    domain: "cyber-compliance",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 95,
    warn: 80,
    definition: "Composite score of endpoint compliance, vulnerability aging, and identity hygiene.",
    formula: "Weighted average of security sub-scores",
    grain: "device × day",
    owner: "CISO",
    source: "CrowdStrike + Tenable",
    refresh: "daily",
    quality: 0.98,
    certified: true,
    lineage: [["Metric: cyb.posture", "certified"]],
  },
  {
    id: "cyb.vulns",
    name: "Critical Vulns",
    domain: "cyber-compliance",
    unit: "count",
    decimals: 0,
    direction: "down",
    target: 0,
    warn: 5,
    definition: "Number of unpatched critical vulnerabilities exceeding SLA.",
    formula: "Count(Vulns WHERE severity='Critical' AND age > SLA)",
    grain: "asset × day",
    owner: "CISO",
    source: "Tenable",
    refresh: "daily",
    quality: 0.99,
    certified: true,
    lineage: [["Tenable", "Scans"]],
  },
  {
    id: "cyb.compliance",
    name: "Policy Compliance",
    domain: "cyber-compliance",
    unit: "%",
    decimals: 0,
    direction: "up",
    target: 99,
    warn: 90,
    definition: "Percentage of systems compliant with baseline security policies.",
    formula: "Compliant Systems / Total Systems",
    grain: "asset × day",
    owner: "CISO",
    source: "Compliance Platform",
    refresh: "daily",
    quality: 0.95,
    certified: true,
    lineage: [["Metric: cyb.compliance", "certified"]],
  }
];

export const MET = Object.fromEntries(METRICS.map(m => [m.id, m]));
